### ISSUE TITLE
Enable Click and Drag to Reorder Modules Under an Engine

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/TagEditorCore#115]
We have disabled click and drag for modules, and I believe this is because its really hard to support moving them between engines.  While that is perfectly OK, it would still be nice if a user could click and drag modules under the same engine so that they can be reordered.  Currently the only way to list the modules in the order that you want is to add them in that order.

**Comment by dsmithni** [comment]
@becega how to solve?

**Comment by becega** [comment]
Drag and drop as Daniel mentions just checks if it can be added to that parent, if the parent allows it to be added, it will be added. And right now it does based on the subnode classes from the parent node. The decision to accept it is all contained in a single subVI called Valid Drag and Drop.
  We can just replace with a custom VI for platypus it doesn't have to be a change in the CEF. Not sure if it will be useful to all the other editors. 
 Now solving this in platypus can be done in 2 ways
1) Inside of this class check for the parent of the current node. If both are the same allow dragging if this is different don't accept the drag. (this will not work if we are using folders but is easier to implement as it doesn't affect the modules and its a change to a single VI).
2) Add a property to the modules to store to what engine they are part of. inside of the ValidDragDrop we would just check the engine of the node and the engine of the parent we want to say it is valid. This will need to change probably the tag bus module parent class to include this property so we can call it in here.
 
 Probably a more generic way can be done, but in this case the restriction to one engine is really specific to this application, restrictions of what is valid or not will vary from configurator to configurator, and they only need to modify this VI. Making this generic will add more complexity to the configuration framework with little gains.

**Comment by Beazurt** [comment]
Looks like we do enable modules to move across engines now.  They get added above the Tags and Mappings though, and the Tags and Mappings Nodes can't be reordered.  I could make a new issue for drag and drop across engines, but wanted to see if this change was intentional first.

**Comment by dsmithni** [comment]
unintentional

**Comment by becega** [comment]
The latest Version of CEF allows Reordering. This is a quick change now just need to update the drop case.
