### ISSUE TITLE
Hang/Race condition when deleting engine if child of engine is selected

### ISSUE THREAD

**Issue by smithed** [LabVIEW-DCAF/TagEditorCore#159]
Steps:
1. Add engine
2. Select taglist or mapping
3. Delete engine
4. Hang :(

You can work around the hang by selecting "exit" from the taskbar but you can't close the error dialog generated for whatever reason, probably its modal but then gets aborted when the taglist ui gets closed/aborted

**Comment by dsmithni** [comment]
can we check if current node is a child of node to-be-deleted and close if it so? Are we already doing that?

**Comment by becega** [comment]
NO longer hangs now Throws and Unhanded error 1556
