### ISSUE TITLE
Deploy tool: handle timeout error

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#189]
Attempting to deploy to a target with an incorrect IP address results in a long (~15 second) timeout followed by an unhandled error 363500 at an unidentified location.

![image](https://cloud.githubusercontent.com/assets/5288961/13022116/d4c48c72-d1a4-11e5-867b-7e1cec5be454.png)

Instead, I'd like a nicely handled error, or at least a custom message.

The timeout is rather long, might want to shorten it as well.

**Comment by becega** [comment]
Might be fixed with latest improvement to the tool

**Comment by pollockm** [comment]
The message is actually less verbose than before (we return the command line error output from pscp).  Apparently the timeout for TCP retries used by pscp comes from the system registry, not a command-line settable input, so this is unlikely to get truly fixed any time soon.

**Comment by jwgorman** [comment]
Acceptance Criteria
- A more helpful error is displayed

**Comment by theSloopJohnB** [comment]
This will be in an upcoming PR, but I want to note it here in case I forget. The error you will get is:

> Verify that you have specified the correct IP Address for your target and that your target is on the network
