### ISSUE TITLE
Progress bar launches twice when launching from the tool menu

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/TagEditorCore#191]
When launching the editor from the tool menu, it launches the splash screen , then the editor, the closes the editor, and launches the splash screen again and then the editor.

**Comment by smithed** [comment]
This is because it takes ages to load the VI, so it launches the splash screen for loading the VI then launches the splash screen for running the VI and loading the classes.

**Comment by tannerblair** [comment]
Thanks smithed, I modified it so that checks for an existing progress bar and uses that one instead so you'll only see one progress bar throughout the launch. I'll do some cleanup and finishing touches early next week and push it.
