### ISSUE TITLE
Fix 'More Information' links in project templates

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#193]
The 'More Information' links in the project templates are broken after migrating the repo to LabVIEW-DCAF.  They currently try to point to http://tbdframework.github.io/

**Comment by smithed** [comment]
renamed repo to LabVIEW-DCAF so the website would continue to work (now its the mouthful "LabVIEW-DCAF.github.io":
https://github.com/LabVIEW-DCAF/LabVIEW-DCAF.github.io

You should also have the fine people at github.com/ni update their page (http://ni.github.io/). @Beazurt

**Comment by becega** [comment]
FIxed it, now it redirects to ni.com/dcaf
