### ISSUE TITLE
Refactor 'rename channel.vi' template

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#200]
Current template first checks for existence of old tag name, then new tag name, then actually does the rename.  Recommend that we use 'get channels' function to get the channel array used for these checks rather than assuming that the configuration is just a channel array.  One less place a user will need to make edits if they have a more interesting config.

**Comment by pollockm** [comment]
Perhaps do the error checks (for whether old name and new name tags exist) in the parent call and core out the rename functionality itself to the user modules, with the assumption that checks have been passed.  Less code overall for folks to write, and less opportunity to make a mistake.

**Comment by becega** [comment]
This should be fixed and replaced with Lines.
