### ISSUE TITLE
VIPC File Should Only Contain TBM Plugins Required for Shipping Examples

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/TagEditorCore#214]
Some of the plugins like EthernetIP and Profibus shouldn't be included in the VIPC file. If we have other examples that use those modules, we can install them with a separate VIPC file. The main VIPC should have the minimum subset needed to run a basic example.

**Comment by becega** [comment]
There will be no VIPC all will be on the Tools Network as individual Files
