### ISSUE TITLE
Auto-include syslog .so in files to deploy to target

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#229]
If Linux target, include by default the correct syslog SO (x86_64 or armv7l) in the list of files to deploy to target.  This is the best available solution for the 'how to get the SO file to the target without annoying the user' problem per conversation with @Beazurt

**Comment by smithed** [comment]
yes, there should be an editor method which lets you add any arbitrary file to the deploy list (get dependency list if i remember correctly)
