### ISSUE TITLE
Allowable instances of module has engine scope - should it have target scope?

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#234]
Example:  LED module.  Each execution target only has one LED to blink.

I can only add one LED module to an engine on a cRIO (because the max instances is 1).  If I add a second engine on the same target, however, I can add LED to each.  Bad.

**Comment by Beazurt** [comment]
I'm 95% certain that target-scope is how this field was originally intended to be used. We just never bubbled this logic all the way up to the target within the editor. I am having a hard time imaging times where it isn't OK to have two instances of a module within an engine, but it is OK to have two instances on the target.

**Comment by smithed** [comment]
I don't think we ever thought about it (I think the N engines concept came up after the M modules concept was settled) but I agree, that makes the most sense.

**Comment by becega** [comment]
I agree it shoudl be Engine scope. Still this gets a little bit trickier, as we can not really go through the tree from inside the node as it will deadlock. So we would either include in the engine a count of modules. OR count the in a FGV. Or add to the engine a way to get all children except the one making the call.

**Comment by becega** [comment]
The discussion in #162 is relevant to this one
