### ISSUE TITLE
Deploy tool: catch error if no/incorrect IP defined for remote target

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#237]
If no target IP address has been defined for a remote target, attempting to deploy to that target gives error 1:
![deploy error](https://cloud.githubusercontent.com/assets/5288961/17595457/c3046812-5fb2-11e6-98bb-734d87163fef.png)

We should intercept this and give a clean DCAF-specific error.

Same for incorrect IP address (timeout error).

**Comment by jwgorman** [comment]
Acceptance Criteria
- Catch these errors, return a DCAF specific error.

**Comment by theSloopJohnB** [comment]
Now will return this error:

> Verify that you have specified the correct IP Address for your target and that your target is on the network.
