### ISSUE TITLE
Basic Execution Template could be cleaned up some

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/TagEditorCore#241]
The stop For Loop is way too big. Wires seem to have too many bends. The second loop uses an odd way to stop. Comments could also be cleaner.

**Comment by becega** [comment]
moved to templates 
https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/47

**Comment by dbendele** [comment]
> second loop uses an odd way to stop.
The constant wired to the stop terminal is certainly not indicative of user code, but it keeps the template simple. Users may implement their own stop mechanism for the loop or remove the loop entirely.
