### ISSUE TITLE
Module timing source selection window is messed up on the engine configuration panel

### ISSUE THREAD

**Issue by fmussi** [LabVIEW-DCAF/TagEditorCore#255]
When I set the Timing source Type to module timing source, the timing source window is badly overlapped with other items on the panel

![image](https://cloud.githubusercontent.com/assets/8535457/20791650/52739a28-b7be-11e6-85bd-819d7096085a.png)

making other controls\indicators hard to see and modify

**Comment by Beazurt** [comment]
This is a duplicate of this issue and has already been closed.

https://github.com/LabVIEW-DCAF/StandardEngine/issues/55
