### ISSUE TITLE
DCAF Tag Editor Core is broken

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/TagEditorCore#272]
The last commit is breaking core. 

C:\Program Files (x86)\National Instruments\LabVIEW 2015\vi.lib\NI\DCAF\Tag Editor Core\Standard Editor\subVI\dialog save before deploy.vi the library.

The library is not claiming it

**Comment by pollockm** [comment]
Oops, failed to save the library...

Matt Pollock
matthew.pollock@ni.com<mailto:matthew.pollock@ni.com>
512-683-9435

________________________________

**Comment by pollockm** [comment]
Fixed in https://github.com/LabVIEW-DCAF/TagEditorCore/commit/3e05c7dfcf5d12d78f3ba6911560dadf2abd75fa
