### ISSUE TITLE
Putty - add user prompt when installing DCAF

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#278]
Customers are reporting confusion about the Putty installer.  let's add a one-button dialog before running the installer to tell folks that we need this and that it is not in fact scary.

**Comment by smithed** [comment]
Putty is also a zero config install, I'd suggest a dialog and then just unzipping it to the vi.lib directory.

Theres also the question of security (in either the current situation or my suggestion). Does VIPM do any verification of the file contents to be sure that the exe you are giving to customers is actually the correct, safe one?
