### ISSUE TITLE
Deleting a highlighted channel from the table removes the channel above it. 

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/TagEditorCore#283]
Found when editing a Scan Engine Module configuration. When attempting to remove a highlighted channel from the "Scan Engine Settings" table, I deleted the channel in the row above. As there is no "undo" feature, a workaround isn't possible.

**Comment by pollockm** [comment]
@leesecho 

After some investigation, this is an issue on the scan engine module, not on the table API (table api is doing what scan engine module's implementation told it to do).  Closing, expect a new issue on the other module.
