### ISSUE TITLE
Define Columns.vi pointing to missing VI

### ISSUE THREAD

**Issue by mcornwall** [LabVIEW-DCAF/TagEditorCore#286]
Test Vis\editor node\Define Columns.vi 
depends on Set Column Width.vi that does not exist in the repository anymore.

**Comment by mcornwall** [comment]
This may be related. The Test Node.lvproj was saved with some dependencies in vi.lib that are part of the Tag Editor Core package and therefor should have been pointing into the Dev environment. Uninstall tag editor core and open the dev version of Test Node.lvproj and you'll see what I'm talking about.

**Comment by pollockm** [comment]
...this project is not used for anything these days, it looks like an old relic from table api development.  Is this bug holding you up in any way?  Would you be sad if we didn't fix it?

**Comment by pollockm** [comment]
Or to put it another way, would a reasonable approach to fixing this be to exclude that directory from the VI Package build rather than making orphaned code happy again?

**Comment by mcornwall** [comment]
My solution was to delete the offending code so that the package would build.
I have no problem if it disappears.

**Comment by pollockm** [comment]
Removed the linkage to the missing VI.  The tageditorcore package already excludes the test vis directory from the package build, so this looks like it's only an issue for folks who are not using our VIPB.
