### ISSUE TITLE
Add INI tokens for standard editor

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#290]
We currently have the ability to right-click on the module editor node's subpanel and show block diagram.  This ability probably shouldn't be there for deployed applications - I'd like to put it behind an INI token that we document.

I suspect there are other features that make sense for a module developer but not for a user of the config editor.  It would be nice if such things could be selectable also, either via INI tokens or via a check of whether it is in dev or run time environment.

**Comment by Beazurt** [comment]
Another example of this that we need a solution for is the scripting tools baked into the editor. Those won't work in a deployed application (assuming the editor is built as an EXE).

**Comment by theSloopJohnB** [comment]
This could also be useful for #303 - we could store the last used config file in an ini file.
