### ISSUE TITLE
Deploy tool: CRIO targets file names with spaces do not transmit

### ISSUE THREAD

**Issue by brbrindle** [LabVIEW-DCAF/TagEditorCore#291]
![image](https://cloud.githubusercontent.com/assets/20828732/23413210/49f137f8-fd95-11e6-8716-4066e0832abc.png)

File names with spaces do not transmit with new SSH transfer methods, showing the above error message. Using old webdav method file names with spaces did work.

**Comment by pollockm** [comment]
Suspected cause: the command line call needs to escape the file name with quotes.

No test case was done with a file containing a space.  Need to add one.

**Comment by jwgorman** [comment]
Acceptance Criteria:
- Files with spaces deploy successfully
- Manually test

**Comment by theSloopJohnB** [comment]
:( This is broken again. I need to make sure this is added to the manual deploy tests.

![image](https://user-images.githubusercontent.com/26978265/26851418-65e78312-4ad0-11e7-82c4-eed03e2ddbf8.png)
