### ISSUE TITLE
SSH deploy method breaks permissions preventing Labview from deploying rtexe

### ISSUE THREAD

**Issue by brbrindle** [LabVIEW-DCAF/TagEditorCore#294]
When including .pcfg in deploy method from Labview development will fail with insufficient permissions if DCAF editor has ever been used to deploy .pcfg file.

problem is avoidable by not including it in RTEXE deployment, however could cause problems later.

**Comment by pollockm** [comment]
We SSH files over using the admin account.   LabVIEW deploys files using the lvuser account.  lvuser cannot overwrite a file owned by admin.

Possible solution: set owner to lvuser on any .pcfg files after deploy as part of command line call to the SCP client.

**Comment by jwgorman** [comment]
Acceptance Criteria
- Deploy first from deploy tool, deploy second from LabVIEW and the deploy works.
- Put in a test to deploy an admin owned file with LabVIEW's code path
