### ISSUE TITLE
GraphViz visualization fails on subsequent loads

### ISSUE THREAD

**Issue by theSloopJohnB** [LabVIEW-DCAF/TagEditorCore#307]
To reproduce:
On the Standard Engine >> Mappings Page, hit the visualize button.
Close out of the visualization.
Re-open the visualization. Now there is nothing being drawn!

Workaround:
Select a different item in the tree pane on the left. Reselect the mappings page, it will work again.

**Comment by Beazurt** [comment]
I've actually tried fixing this twice now and gave up both times. I have absolutely no clue why this happens, but it is something strange with the behavior of the control being used and/or the dot.exe. I'd love help figuring this out, but at least for me this is not a simple fix.
