### ISSUE TITLE
deprecate/remove github releases

### ISSUE THREAD

**Issue by smithed** [LabVIEW-DCAF/TagEditorCore#331]
eg https://github.com/LabVIEW-DCAF/TagEditorCore/releases
the last one is from 2014 so it could be confusing to go in there and download a version thats several years out of date :)

**Comment by theSloopJohnB** [comment]
Deprecate / Delete old releases. Github release will only be done on DCAF Core repository.

**Comment by pollockm** [comment]
Fixed.
