### ISSUE TITLE
Scripting module includes VI crashes labview 2017 with attached config

### ISSUE THREAD

**Issue by theSloopJohnB** [LabVIEW-DCAF/TagEditorCore#333]
This config file: [test-config.zip](https://github.com/LabVIEW-DCAF/TagEditorCore/files/1157445/test-config.zip)

Does not behave well with LabVIEW 2017. I need to try it out with other versions with other versions of LabVIEW. Note! This configuration file requires all the DCAF modules on VIPM in order to work.

If you try and script the module includes.vi, you get the following error:
![image](https://user-images.githubusercontent.com/26978265/28342405-b0488608-6bdd-11e7-801d-d05384fc2484.png)
Suspiciously, it mentions EIP in the reporter. I downloaded and attached the NIER report as well, in case it is helpful.
[error-report.zip](https://github.com/LabVIEW-DCAF/TagEditorCore/files/1157466/error-report.zip)

The configuration was created by making a PC target, one standard engine, and all possible modules I could put under it.

More investigation is required.

**Comment by smithed** [comment]
EIP is the x86 instruction pointer register.

**Comment by theSloopJohnB** [comment]
I did some more work on it this morning. 

I thought that maybe it was a trouble module, or a combination of modules that was the issue. I attempted to script by cutting out half of the modules - still had a crash. I thought I was on the right track. I then attempted to build a configuration file one module at a time, seeing which one being added produced a crash. This time, I had no crash! I tried deleting the contents of my includes VI in order to script it from a fresh slate - no crash. 

Then I tried to reproduce it with the original file attached to this issue. No crash this time!

I don't know why the crash stopped happening.

I want to see if anyone else can reproduce this and then decide what to do.

**Comment by dbendele** [comment]
did not reproduce crash in LV 2014,
with attached configuration, scripting resulted in prompt to Find control named:
"ethernetip.lvlib:etherneti[.ctl" (which I canceled and ignored future prompts) 
Target Includes VI included all runtime objects except  Ethernet IP runtime

**Comment by jwgorman** [comment]
Closing non-reproducible
