### ISSUE TITLE
GraphViz Mapping UI button not entirely clickable

### ISSUE THREAD

**Issue by jbellamyNI** [LabVIEW-DCAF/TagEditorCore#361]
If you click on the actual image in the center of the button in the Manual Mapping pane, the button will not detect the event. This can be worked around by clicking on the outer edges of the button.

Basically, you cannot click inside of the red box shown below:
![image](https://user-images.githubusercontent.com/31747148/30879650-935bd7a6-a2c5-11e7-8a5d-734d85c705f8.png)

I'm assuming this is caused by the overlaid image not being clickable.

**Comment by dbendele** [comment]
Export to CSV button suffered from the same symptoms and was also addressed in commit
https://github.com/LabVIEW-DCAF/TagEditorCore/pull/365/commits/6326c08e11b3fb7c99aeff22e2cc1d42d618f1d8
