### ISSUE TITLE
Need a Better Mechanism for Channel Modification (Scaling, Chunking, Calibration etc.)

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/TagEditorCore#93]
Today functionality that modifies the value of a channel, or refactors a channel into more or fewer channels, must be implemented as a process function.  This is problematic because there are potentially two places where that modification must be done, after any inputs and after processing occurs but before outputs.  This means that a channel modification module can only perform that modification in one of those two places, causing a cycle delay in the other.  Alternatively a user can add two scaling modules, but they have to be very careful about module execution order, and the UX is probably not intuitive for them.  

I think this functionality needs a new mechanism within the framework.  It could be that we add scaling directly to channels somehow.  Alternatively we could add two new execution hooks either within the engine or within the TBM framework for post input and post processing channel modification (maybe this can give us our forcing functionality as well?).  Ideally the solution would also allow the engine to ignore the raw channel values if they are of no use to the end user (unlike our solution today).  This could also potentially be a completely different type of execution plugin (not a TBM), so that it could be reused more intuitively in other projects.

**Comment by becega** [comment]
We dont have Process functions any more.  Also there is a new scaling module and some changes to enable it.
